# Generated by Django 4.2.6 on 2023-12-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tlkapi", "0020_printrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderinfo",
            name="OriginalBinNumber",
            field=models.IntegerField(default=0, verbose_name="Orig Bin Number"),
            preserve_default=False,
        ),
    ]
