# Generated by Django 4.2.6 on 2023-10-12 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0007_producttype_product_title"),
        ("tlkapi", "0021_alter_printrequest_done"),
    ]

    operations = [
        migrations.AddField(
            model_name="printrequest",
            name="Variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tools.variant",
                verbose_name="Variant",
            ),
        ),
    ]
