# Generated by Django 4.2.5 on 2023-12-08 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlkapi', '0021_orderinfo_originalbinnumber'),
        ('tlkapi', '0022_printrequest_variant'),
    ]

    operations = [
    ]
