# Generated by Django 4.2.6 on 2023-12-08 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tlkapi", "0023_merge_20231208_0732"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderinfo",
            name="OriginalBinNumber",
            field=models.IntegerField(default=0, verbose_name="Orig Bin Number"),
        ),
    ]
