# Generated by Django 4.2.6 on 2023-11-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0007_producttype_product_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="variant",
            name="image_id",
            field=models.PositiveBigIntegerField(default=0, verbose_name="Image Id"),
            preserve_default=False,
        ),
    ]
