# Generated by Django 4.2.6 on 2023-11-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0008_variant_image_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="variant",
            name="image_src",
            field=models.URLField(blank=True, null=True, verbose_name="Image Source"),
        ),
    ]
