# Generated by Django 4.2.6 on 2023-11-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0009_variant_image_src"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variant",
            name="image_id",
            field=models.PositiveBigIntegerField(default=0, verbose_name="Image Id"),
        ),
    ]
