# Generated by Django 4.2.6 on 2023-11-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0010_alter_variant_image_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variant",
            name="image_id",
            field=models.PositiveBigIntegerField(null=True, verbose_name="Image Id"),
        ),
    ]
