# Generated by Django 4.2.6 on 2023-11-23 00:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0011_alter_variant_image_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="has_backprint",
            field=models.BooleanField(default=False, verbose_name="Has Back Print"),
        ),
    ]
