# Generated by Django 4.2.6 on 2024-01-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0013_product_created_at_product_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_virtual',
            field=models.BooleanField(default=False, verbose_name='Virtual Product'),
        ),
    ]
